services:
  - type: web
    name: backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=512
      - key: KEEPALIVE_URL
        value: https://credits-core.onrender.com/start-server
